### ISSUE TITLE
Handlers & logic for authenticated routes

### ISSUE THREAD

**Issue by jbecker01** [USSF-ORBIT/ussf-portal-client#126]
- Add a placeholder un-authenticated page with a button to initialize a SAML request
- Add logic to all existing beta pages that requires authentication and redirects to the login page if there is no session
- Existing MVP pages should not be affected
- Display user first/last name in Personal Data
- Add Log Out button to Beta pages (https://www.figma.com/file/iPOdDkRxCaeoDoQ4JXjxlk/Space-Force-Service-Portal?node-id=2688%3A30769)

**Comment by suzubara** [comment]
- E2E test that can't access MVP or beta pages without being logged in (redirect back to login page)
- Add require session/user helpers for both static pages & server pages (https://nextjs.org/docs/authentication)
- Display user data in PersonalData on beta
- Add log out button
