### ISSUE TITLE
Set up Cypress CI in Github Actions

### ISSUE THREAD

**Issue by suzubara** [USSF-ORBIT/ussf-portal-client#22]
https://docs.cypress.io/guides/continuous-integration/github-actions#Cypress-GitHub-Action

**Comment by suzubara** [comment]
@esacteksab The Cypress dev team has an official Github action but it is not "verified" by Github: https://github.com/marketplace/actions/cypress-io

Are you ok with us adding it to our allowed actions?

**Comment by esacteksab** [comment]
Looks like they're trying to get verified https://github.com/cypress-io/github-action/issues/305#issuecomment-832021887

Nothing sticks out. Let's pin to a specific release and go for it. 

Thanks!
