### ISSUE TITLE
Bookmarks break out of the collection border

### ISSUE THREAD

**Issue by jbecker01** [USSF-ORBIT/ussf-portal-client#245]
Actual: When resizing the browser window, between a width of 1025 and 1180, the bookmarks will spill out of the collection border. 

Expected: Collections will resize accordingly so that bookmarks will always appear contained within the border of a collection.

Steps to reproduce:
1. launch browser
2. enter https://232-delete-link--ussf-portal-client.netlify.app/joinbeta into the address bar
3. resize the browser window to a width anywhere between 1025 and 1180
4. notice the bookmarks themselves will spill out of the collection border

Browser: Chrome / Safari / FF

Screenshots:
![Screen Shot 2021-09-28 at 9 20 07 AM](https://user-images.githubusercontent.com/52676444/135177418-f4111f42-40c7-45f6-a6ae-eee4ea14c506.png)

**Comment by suzubara** [comment]
@jbecker01 I believe this will be fixed in https://github.com/USSF-ORBIT/ussf-portal-client/pull/249 !
