### ISSUE TITLE
News and Announcements listing page

### ISSUE THREAD

**Issue by jbecker01** [USSF-ORBIT/ussf-portal-client#262]
**Summary:**
Build a landing page for all news and announcements published through the CMS and SpaceForce.mil RSS feed.

**URL:** `/news`

**Design:** https://www.figma.com/file/iPOdDkRxCaeoDoQ4JXjxlk/Space-Force-Service-Portal?node-id=3349%3A33661

**Page content:**
- Title: Latest News
- Sub-title: Publicly released Space Force news released within the last 30 days
- Display content from the SpaceForce.mil RSS feed
- The last four pieces of published content ordered by date
- Each piece of content will display:
     - Thumbnail image
     - Publication date
     - Title
     - Description/excerpt
- The title of RSS content will link out to the SpaceForce.mil article
- Display icon next to each article letting the user know they will be directed to another site other than the portal to view the content.

**Follow up issues:**
- [ ] Latest news and Archived news toggle buttons.
    - The default view will be Latest news
    - Articles older than the 4 most recent will be moved to the Archived News page. If no news is published to the page within 30 days then keep the last four pieces of content on the page.
- [ ] Display CMS content on this page in addition to RSS items

**Comment by MKDale** [comment]
Link to full N&A page in Figma is here: https://www.figma.com/file/iPOdDkRxCaeoDoQ4JXjxlk/Space-Force-Service-Portal?node-id=3349%3A33661
