### ISSUE TITLE
Add Matomo tracking client to the portal pages

### ISSUE THREAD

**Issue by jbecker01** [USSF-ORBIT/ussf-portal-client#316]
Add the Matomo analytics tracking code to the following pages:
- [x] Login 
- [x] My Space
- [x] All sites & applications

**Comment by suzubara** [comment]
@jbecker01 We may want to start a doc with all tracking events & params we want to send. We will send a page view event for each internal URL that is visited, and for each `trackEvent` call we need a category, action, and optionally name.

We can also track clicks to external links. The full reference is here: https://developer.matomo.org/api-reference/tracking-javascript

**Comment by suzubara** [comment]
I added a separate issue for implementing the event tracking, since that is slightly different than the page tracking: https://github.com/USSF-ORBIT/ussf-portal-client/issues/471
