### ISSUE TITLE
Apollo federation to support multiple GraphQL APIs

### ISSUE THREAD

**Issue by suzubara** [USSF-ORBIT/ussf-portal-client#346]
When we stand up hosted Keystone, we will also need to configure Apollo Federation in order to be able to consume multiple GraphQL APIs in the portal app.

**Comment by abbyoung** [comment]
## Tasks
* Understand problem we're trying to solve with our APIs
* Understand work required to implement Apollo Federation
* Decide if Apollo Federation is required at this time, and if not, how to integrate Keystone API alongside our internal portal API.

## Outcome

### Problem Statement
We need to continue to access our Next.js GraphQL endpoint, which queries the DocumentDB instance, while adding support for an external Keystone app GraphQL API.

At this time, these are the only two data sources the portal is ingesting.

### Apollo Federation Workflow
* Break graph into subgraphs
* Each subgraph is its own service
* Compose these subgraphs into supergraph (using @apollo/rover)
* Create gateway and pass in supergraph
* Access GraphQL API through this gateway

### Constraints
Apollo Federation requires each subgraph to run as its own microservice/Apollo Server. This presents a problem with our current Next.js architecture. Ideally, they should each be a separate service, not part of the Next.js app.

We currently run our Apollo Server in a Next.js API route, `/api/graphql`, which uses `apollo-server-micro` and serves one graph at this endpoint. Attempting to chain these micro instances in other endpoints, all accessed via a gateway endpoint, proved to be a challenge. Whether it was strictly the server architecture or a subgraph/GraphQL problem, I'm not sure. It felt like building a house of cards and definitely not something I'd recommend putting into production.

### Solution
The good news is, there's an easier way -- **using multiple links in a single Apollo Client.**

Source: [Next.js + Multiple Apollo Clients & GraphQL Sources](https://www.loudnoises.us/next-js-two-apollo-clients-two-graphql-data-sources-the-easy-way/)

* Create `HttpLink` for Next.js GraphQL endpoint
* Create `HttpLink` for Keystone GraphQL endpoint
* Pass both into ApolloClient and use `ApolloLink.split()` to determine use based on context
* Pass in context to `useQuery` or `useMutation`

```
// In apolloClient.tsx

const cmsLink = new HttpLink({
  uri: '<keystone>/api/graphql',
  fetchOptions: {
    contentType: 'application/json',
    headers: {
      'Access-Control-Allow-Origin': <cors settings here>,
      'Access-Control-Allow-Headers' <cors settings here>
    }
  }
})

const portalLink = new HttpLink({
  uri: '/api/graphql'
})
...

export const client = new ApolloClient({
  link: ApolloLink.split(
    (operation) => operation.getContext().clientName === 'cms',
    cmsLink,
    portalLink
})

```

```
// Pass in context to queries/mutations

useQuery(GET_COLLECTIONS, {
  context: {
    clientName: 'cms',
  }
})

```

**CORS**: CORS will need to be handled when creating the HttpLink for the cms endpoint, and in `Keystone.ts` [server config](https://keystonejs.com/docs/apis/config#server). CORS middleware docs [can be found here](https://www.npmjs.com/package/cors#configuration-options).
