### ISSUE TITLE
Update select collections button label

### ISSUE THREAD

**Issue by jbecker01** [USSF-ORBIT/ussf-portal-client#433]
Update the "Select Collections" button label to "Select Multiple Collections" on the Sites and Applications page.

**Comment by suzubara** [comment]
@jbecker01 Didn't this button say `Select Multiple Collections` to begin with? are we just changing it back? Also, none of the other buttons are title-case, so should it be `Select multiple collections`?

**Comment by jbecker01** [comment]
We are changing it back. You are correct, the label should be Select multiple collections.
