### ISSUE TITLE
Maximum collections per MySpace (25)

### ISSUE THREAD

**Issue by suzubara** [USSF-ORBIT/ussf-portal-client#438]
Limit users from adding more than 25 collections to My Space.

- Need UX designed communicating this limit to the user
- Need error state if user attempts to do this anyways

Add disabled state to button styles (45% opacity)

**Comment by MKDale** [comment]
Thinking lean-ly, I say we start with this approach. At the point when the user reaches the 25 max collections on their My Space page, we simply remove the 'Add Section' prompt area. We'll go without a notification as to why for now (as to not preemptively assume that we need one and the user won't instinctively understand). https://www.figma.com/file/iPOdDkRxCaeoDoQ4JXjxlk/Space-Force-Service-Portal?node-id=3256%3A33126

**Comment by suzubara** [comment]
@MKDale sounds good! In that case, we'd also hide the "Select multiple collections" button on the Sites & Applications page.. does that sound right?

**Comment by suzubara** [comment]
Dependent on https://github.com/USSF-ORBIT/ussf-portal-client/issues/477
