### ISSUE TITLE
Maximum links per collection (10)

### ISSUE THREAD

**Issue by suzubara** [USSF-ORBIT/ussf-portal-client#439]
Limit users from adding more than 10 links to a collection in My Space.

- Need UX designed communicating this limit to the user
- Need error state if user attempts to do this anyways

**Comment by MKDale** [comment]
There's a page in Figma for custom links warning of max limit: https://www.figma.com/file/iPOdDkRxCaeoDoQ4JXjxlk/Space-Force-Service-Portal?node-id=3258%3A34253

And another page in Figma for a system link warning within the dropdown when the user reaches and tries to add only the 10th link: https://www.figma.com/file/iPOdDkRxCaeoDoQ4JXjxlk/Space-Force-Service-Portal?node-id=3258%3A34689

**Comment by suzubara** [comment]
Dependent on https://github.com/USSF-ORBIT/ussf-portal-client/issues/477
