### ISSUE TITLE
The "Join beta" button is not shown on screen resolutions where the bottom of the left column is off the page

### ISSUE THREAD

**Issue by noahfirth** [USSF-ORBIT/ussf-portal-client#456]
We should look at the layout of the home page to see if we can move / resposition the "Join beta" button to make sure it is visible for people n government laptops / devices where the screen resolution is low.

This was found by @K-Jurick who has some screenshots to share.

**Comment by jbecker01** [comment]
Solutions are:
- Make the left nav scrollable
- Include the Join Beta button in the mobile navigation
- Swap out the Guardians Enlisted Rank Insignia news announcement with a link to the beta. The copy would be: "Join the beta"
