### ISSUE TITLE
The ability to edit the name of a collection comes when you click the name and is not available in the dropdown of the gear; this may not be obvious to people right away

### ISSUE THREAD

**Issue by jbecker01** [USSF-ORBIT/ussf-portal-client#464]
Add an option to the dropdown menu from the cog icon to edit the collection name.

**Comment by MKDale** [comment]
Naming a new collection and re-naming an existing collection via the settings dropdown, including what will be displayed if a user cancels action with no input in the field: https://www.figma.com/file/iPOdDkRxCaeoDoQ4JXjxlk/?node-id=3264%3A33719

**Comment by suzubara** [comment]
👍  Should we also remove the ability to edit a collection name by clicking on it? I think it might help keep things simple

**Comment by suzubara** [comment]
> 👍 Should we also remove the ability to edit a collection name by clicking on it? I think it might help keep things simple

discussed in Slack, confirmed we should remove this so the only way to edit the name is via the gear dropdown.
