### ISSUE TITLE
UX/UI updates to the "Add link" flow

### ISSUE THREAD

**Issue by jbecker01** [USSF-ORBIT/ussf-portal-client#465]
New flow: https://www.figma.com/file/iPOdDkRxCaeoDoQ4JXjxlk/Space-Force-Service-Portal?node-id=3228%3A31669

Changes:
- Modify the Add Custom Link modal to include text fields for both Name & URL (both required, URL must be valid)
- When typing in the Add Link ComboBox, display the "Add Custom Link" option if no results are found. Selecting this option opens the modal.
- Display the Custom Link Icon on custom bookmarks, with an edit icon instead of delete
- Clicking the edit icon opens the Custom Link modal with a delete button. User can modify the URL and/or name of the link here.

**Comment by MKDale** [comment]
The new UX flow is here on this page. Red lined comments for engineers are on the second line. In Figma, "For Eng: Add custom link" page https://www.figma.com/file/iPOdDkRxCaeoDoQ4JXjxlk/?node-id=3228%3A31669
