### ISSUE TITLE
Display RSS feed from spaceforce.mil

### ISSUE THREAD

**Issue by jbecker01** [USSF-ORBIT/ussf-portal-client#50]
This feature will display a listing of all the news articles available through the spaceforce.mil RSS news feed. 

Acceptance criteria:
- A service member can see a news page containing a listing of all the news articles available through the RSS feed
- A service member can click on an article and be routed to the article that's hosted on spaceforce.mil
- The article will open up in a new tab

Design requirements:
- Each article in the feed will display the following:
     - title
     - publication date
     - description/excerpt
     - link to the full article on spaceforce.mil
     - source (ie, “Secretary of the Air Force Public Affairs”)
      - image URL  
- Display icon next to each article letting the user know they will be directed to another site other than the portal to view the content. 
- Designs: https://www.figma.com/file/iPOdDkRxCaeoDoQ4JXjxlk/Space-Force-Service-Portal?node-id=3349%3A33661

**Comment by MKDale** [comment]
Design for the N&A section on My Space is here in Figma: https://www.figma.com/file/iPOdDkRxCaeoDoQ4JXjxlk/Space-Force-Service-Portal?node-id=3351%3A33837

**Comment by suzubara** [comment]
@jbecker01 I think all of this work is already encapsulated by https://github.com/USSF-ORBIT/ussf-portal-client/issues/262
Can we close this as a duplicate?
