### ISSUE TITLE
Formalize DB & ODM decisions

### ISSUE THREAD

**Issue by jbecker01** [USSF-ORBIT/ussf-portal-client#86]
Write an ADR describing our chosen architecture & tools for the portal database (_not_ the CMS database), including what we'll use to connect to it (ie, ODM). Note that we already have an [ADR for deciding to use NoSQL](https://github.com/USSF-ORBIT/ussf-portal/blob/main/docs/adr/0004-nosql-for-nexjs.md) so this ADR does not need to cover that.

As part of making this decision, this issue may include spike-work to compare different Mongo+NextJS approaches in the code.

**Comment by abbyoung** [comment]
PR: https://github.com/USSF-ORBIT/ussf-portal/pull/66

**Comment by suzubara** [comment]
Closed by https://github.com/USSF-ORBIT/ussf-portal/pull/66
